[build]
  publish = "."
  functions = "api"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[build.environment]
  NODE_VERSION = "18"
  DATABASE_URL = "postgresql://neondb_owner:npg_wBxuRO8jN7KX@ep-wild-shadow-aej6461z-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

# Auto-deploy settings
[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200