[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/admin"
  to = "/admin/login.html"
  status = 302

[[redirects]]
  from = "/admin/"
  to = "/admin/login.html"
  status = 302

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"